assets:
  - probossh.tar.gz
steps:
  - name: Add php7
    plugin: Script
    script: |
      echo 'exit 0' > /usr/sbin/policy-rc.d
      apt-get update
      apt-get install -y software-properties-common language-pack-en-base
      LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php
      apt-get update
      DEBIAN_FRONTEND=noninteractive apt-get install -y php7.0 libapache2-mod-php7.0 php7.0-gd php7.0-curl php7.0-json php7.0-mbstring php7.0-mysql php7.0-mcrypt php7.0-imagick php7.0-dev php7.0-gmp php7.0-xml php7.0-bcmath php7.0-redis php7.0-uploadprogress php7.0-soap php7.0-pgsql php7.0-ldap php7.0-yaml
      cp /etc/php5/mods-available/general_settings.ini /etc/php/7.0/apache2/conf.d/20-general_settings.ini
      echo 'memory_limit=-1' > /etc/php/7.0/cli/conf.d/30-cli_memory_limit.ini
      a2dismod php5
      a2enmod php7.0
      a2enmod mpm_prefork
      apache2ctl graceful
  - name: opcache
    plugin: Script
    script: |
      echo 'opcache.enable=1' >> /etc/php/7.0/mods-available/opcache.ini
      echo 'opcache.enable_cli=1' >> /etc/php/7.0/mods-available/opcache.ini
      echo 'opcache.memory_consumption=192' >> /etc/php/7.0/mods-available/opcache.ini
      echo 'opcache.interned_strings_buffer=16' >> /etc/php/7.0/mods-available/opcache.ini
      echo 'opcache.max_accelerated_files=3907' >> /etc/php/7.0/mods-available/opcache.ini
      echo 'opcache.validate_timestamps=0' >> /etc/php/7.0/mods-available/opcache.ini
      echo 'opcache.fast_shutdown=1' >> /etc/php/7.0/mods-available/opcache.ini
      apache2ctl graceful
  - name: Import SSH Keys
    command: 'tar -C $HOME/.ssh -zxvf $ASSET_DIR/probossh.tar.gz ; ls -al $HOME/.ssh'
  - name: Build Drupal
    plugin: Script
    script:
      - composer self-update ; composer global update
      - cd /src
      - composer install --ansi
      - composer require "ucdavis/sitefarm:dev-release-8.x-1.0" --ansi
      - composer require "ucdavis/sitefarm_one:dev-release-8.x-1.0" --ansi
  - name: Drupal site setup
    plugin: Drupal
    drupalVersion: 8
    subDirectory: docroot
    runInstall: true
    profileName: sitefarm
    installArgs: '--site-name="Testing Acquia SiteFarm on Probo" --account-pass=probo --account-mail=wdtest@ucdavis.edu'
  - name: Fix files directory permissions
    command: 'chown -R www-data:www-data /var/www/html/sites/default/files'
  - name: Run Behat NoJS
    plugin: Script
    script:
      - cp $SRC_DIR/behat.probo.yml /var/www/html/profiles/sitefarm/behat.yml
      - cp -r $SRC_DIR/tests/features/acquia /var/www/html/profiles/sitefarm/tests/features/.
      - cd /var/www/html/profiles/sitefarm
      - $SRC_DIR/vendor/bin/behat --profile probo --tags "~@javascript" --colors
  - name: Run behat js tests
    command: 'wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar > /dev/null 2>&1 ; apt-get install xvfb -y ; xvfb-run java -jar selenium-server-standalone-2.53.0.jar > /dev/null 2>&1 & sleep 5 ; cd /var/www/html/profiles/sitefarm ; $SRC_DIR/vendor/bin/behat --profile probo --tags "@javascript" --colors ; disown'