image: proboci/ubuntu:20.04-php8.1
assets:
  - probossh.tar.gz
  - bitbucket_auth.sh
  - probo-settings.php
phpIniOptions:
  upload_max_filesize: 64M
  post_max_size: 64M
  memory_limit: 512M
steps:
  - name: Import SSH Keys
    plugin: Script
    script:
      - mkdir $HOME/.ssh
      - tar -C $HOME/.ssh -zxvf $ASSET_DIR/probossh.tar.gz
      - chmod 600 $HOME/.ssh/id_rsa*
      - ssh-keyscan -H bitbucket.org >> $HOME/.ssh/known_hosts
      - ls -al $HOME/.ssh
  - name: Build Drupal
    plugin: Script
    script:
      - apt-get update > /dev/null 2>&1
      - apt-get install jq xvfb -y > /dev/null 2>&1
      - . $ASSET_DIR/bitbucket_auth.sh >/dev/null 2>&1
      - PULL_REQUEST_ID=$(basename "https://bitbucket.org/ietwebdev/sitefarm-acquia/pull-requests/${PULL_REQUEST_LINK}")
      - API_DATA=$(curl -s --user $BITBUCKET_USER:$BITBUCKET_PASS https://api.bitbucket.org/2.0/repositories/ietwebdev/sitefarm-acquia/pullrequests/${PULL_REQUEST_ID})
      - DESTINATION_BRANCH=$(jq -r  '.destination.branch.name' <<< "${API_DATA}")
      - composer self-update
      - echo $PATH
      - cd /src
      - if [ $(git ls-remote --heads git@bitbucket.org:ietwebdev/sitefarm.git $BRANCH_NAME | wc -l) = 1 ]; then BRANCH_PROFILE="$BRANCH_NAME"; elif [ $(git ls-remote --heads git@bitbucket.org:ietwebdev/sitefarm.git $DESTINATION_BRANCH | wc -l) = 1 ]; then BRANCH_PROFILE="$DESTINATION_BRANCH"; else BRANCH_PROFILE=dev; fi
      - if [[ $BRANCH_PROFILE =~ ^[0-9]{1,2}\.x$ ]]; then VERSION="$BRANCH_PROFILE-dev"; else VERSION="dev-$BRANCH_PROFILE"; fi
      - composer require "ucdavis/sitefarm:$VERSION" --ansi
  - name: Update Node and install NPM packages
    plugin: Script
    script: |
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      which nvm
      nvm install 14.15.0 > /dev/null 2>&1
      nvm alias default 14.15.0 > /dev/null 2>&1
      npm -v
      node -v
      cd $SRC_DIR/docroot/profiles/sitefarm/themes/sitefarm_one
      npm ci --unsafe-perm
  - name: Run PhpUnit
    plugin: Script
    script:
      - cd $SRC_DIR/docroot/profiles/sitefarm
      - SYMFONY_DEPRECATIONS_HELPER=disabled $SRC_DIR/vendor/bin/phpunit --colors="always"
  - name: Drupal site setup
    plugin: Drupal
    drupalVersion: 9
    subDirectory: docroot
    runInstall: true
    profileName: sitefarm
    installArgs: '--site-name="Testing Acquia SiteFarm on Probo" --account-pass=probo --account-mail=wdtest@ucdavis.edu -y'
    settingsRequireFile: $ASSET_DIR/probo-settings.php
    settingsAppend: '$settings["file_private_path"] = "/var/www/html/sites/default/private-files"; $settings["config_sync_directory"] = "sites/default/files/config_XFJgWG0OOBwFg8asfsKWO8sMf6eYyOq5dbrv14FqkavRVEY6j61JoCbiJ9T_rqphSfdKjkD2Kw/sync"; putenv("TEST_SESSION_ENABLED=true");'
    phpIniOptions:
      upload_max_filesize: 256M
      post_max_size: 256M
      memory_limit: 512M
  - name: Install default content
    plugin: Script
    script:
      - drush version
      - drush scr "$SRC_DIR/factory-hooks/post-install/default_content.php"
      - drush cr
  - name: Fix files directory permissions
    plugin: Script
    script:
      - chown -R www-data:www-data /var/www/html/sites/default/private-files
      - chown -R www-data:www-data /var/www/html/sites/default/files
  - name: Install Cypress
    plugin: Script
    script:
      # Enable testing modules.
      - cd $SRC_DIR/docroot
      - drush pm-enable sitefarm_cypress --yes
      # Install Cypress and node dependencies.
      - cd $SRC_DIR/docroot/profiles/sitefarm/tests/cypress
      - npm ci
  - name: Run Cypress
    plugin: Script
    script:
      # Set environment variables and run Cypress.
      - cd $SRC_DIR/docroot/profiles/sitefarm/tests/cypress
      - export CYPRESS_DRUPAL_BASE_URL='http://localhost'
      - export CYPRESS_BASE_URL='http://localhost'
      - npm run test:ci -- --quiet --browser chrome
