assets:
  - probossh.tar.gz
steps:
  - name: Import SSH Keys
    command: 'tar -C $HOME/.ssh -zxvf $ASSET_DIR/probossh.tar.gz ; ls -al $HOME/.ssh'
  - name: Build Drupal
    command: 'composer self-update ; composer global update ; cd /src ; composer install'
  - name: Drupal site setup
    plugin: Drupal
    drupalVersion: 8
    subDirectory: docroot
    runInstall: true
    profileName: sitefarm
    installArgs: '--site-name="Testing Acquia SiteFarm on Probo" --account-pass=probo --account-mail=wdtest@ucdavis.edu'
  - name: Run Behat NoJS
    plugin: Script
    script:
      - cp $SRC_DIR/behat.probo.yml /var/www/html/profiles/sitefarm/behat.yml
      - cp -r $SRC_DIR/tests/features/acquia /var/www/html/profiles/sitefarm/tests/features/.
      - cd /var/www/html/profiles/sitefarm
      - $SRC_DIR/bin/behat --profile probo --tags "~@javascript"
  - name: Run behat js tests
    command: 'wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar > /dev/null 2>&1 ; apt-get install xvfb -y ; xvfb-run java -jar selenium-server-standalone-2.48.2.jar > /dev/null 2>&1 & sleep 5 ; cd /var/www/html/profiles/sitefarm ; $SRC_DIR/bin/behat --profile probo --tags "@javascript" ; disown' 