# Extending stack-acquia.yml
version: "3.9"

services:
  # CLI
  cli:
    extends:
      file: ${HOME}/.docksal/stacks/stack-acquia.yml
      service: cli
    environment:
      - PHP_IDE_CONFIG
      - 'TEST_SESSION_ENABLED=true'
    ports:
      - 9003

  # Browser
  browser:
    hostname: browser
    image: selenium/standalone-chrome-debug:3.141.59-oxygen
    volumes:
      # Project root volume
      - project_root:/var/www:ro,nocopy
    ports:
      - "${VNC_PORT_MAPPING:-5900}"
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
