#!/usr/bin/env bash

#-------------------------- Settings --------------------------------

# PROJECT_ROOT is passed from fin.
# The following variables are configured in the '.env' file: DOCROOT, VIRTUAL_HOST.

SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------


# Set docksal-local.env
cp $PROJECT_ROOT/.docksal/example.docksal-local.env $PROJECT_ROOT/.docksal/docksal-local.env
# Start containers
fin up
# Install
composer install
# Set local config files
cp $SITEDIR_PATH/default.settings.local.php $SITEDIR_PATH/settings.local.php
cp $SITEDIR_PATH/default.services.local.yml $SITEDIR_PATH/services.local.yml
# Set config
fin hosts add $VIRTUAL_HOST
echo "
\$databases['default']['default'] = array (
  'database' => 'default',
  'username' => 'user',
  'password' => 'user',
  'prefix' => '',
  'host' => '$(fin vm ip)',
  'port' => '33061',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);
" >> docroot/sites/default/settings.local.php
# Install site
cd $DOCROOT
fin drush site-install sitefarm -y --site-name="SiteFarm Acquia"
# Get login link
fin drush uli
# Set permissions
sudo chmod 755 $SITEDIR_PATH
git checkout -- $SITEDIR_PATH/settings.php