#!/usr/bin/env bash

## Do a fresh Drupal installation of the SiteDen profile. Be sure to have xDebug disabled.
##
## Usage: fin reinstall [arguments]

# Start containers
fin up

# Install site
cd "${PROJECT_ROOT}/${DOCROOT}"
fin drush site-install sitefarm -y --site-name="SiteFarm Acquia" $@

# Install default content
fin drush en sitefarm_default_content -y

# Disable unnecessary modules
fin drush pmu hal serialization rest default_content sitefarm_default_content -y

# Get login link
fin drush uli --uri="http://$VIRTUAL_HOST"